version: '3.5'

services:
  dockcode:
    image: mateuszncia/dockcode:latest
    restart: unless-stopped
    environment:
      DOCKCODEPASS: <YOU_PASSWORD_HERE>
    ports:
      - 80:8080
    volumes:
      - userspace:/home/dockcode
volumes:
  userspace:
